`timescale 1ns / 1ps

module captainusb_pcie_minimal_a7 (
    input  wire       clk_sys,
    input  wire       rst,

    output wire [0:0] pcie_tx_p,
    output wire [0:0] pcie_tx_n,
    input  wire [0:0] pcie_rx_p,
    input  wire [0:0] pcie_rx_n,
    input  wire       pcie_clk_p,
    input  wire       pcie_clk_n,
    input  wire       pcie_perst_n,

    output wire       pcie_user_clk,
    output wire       pcie_user_reset,
    output wire       pcie_link_up,

    output wire [63:0] m_axis_rx_tdata,
    output wire [7:0]  m_axis_rx_tkeep,
    output wire        m_axis_rx_tlast,
    output wire        m_axis_rx_tvalid,
    input  wire        m_axis_rx_tready,
    output wire [21:0] m_axis_rx_tuser,

    input  wire [63:0] s_axis_tx_tdata,
    input  wire [7:0]  s_axis_tx_tkeep,
    input  wire        s_axis_tx_tlast,
    input  wire        s_axis_tx_tvalid,
    output wire        s_axis_tx_tready,
    input  wire [3:0]  s_axis_tx_tuser,

    output wire [15:0] cfg_completer_id,

    input  wire        cfg_interrupt,
    input  wire        cfg_interrupt_assert,
    input  wire [7:0]  cfg_interrupt_di,
    input  wire [4:0]  cfg_pciecap_interrupt_msgnum,
    input  wire        cfg_interrupt_stat,
    output wire        cfg_interrupt_rdy,
    output wire [7:0]  cfg_interrupt_do,
    output wire [2:0]  cfg_interrupt_mmenable,
    output wire        cfg_interrupt_msienable,
    output wire        cfg_interrupt_msixenable,
    output wire        cfg_interrupt_msixfm
);
    wire pcie_refclk;
    wire user_app_rdy;
    wire [7:0] cfg_bus_number;
    wire [4:0] cfg_device_number;
    wire [2:0] cfg_function_number;

    assign cfg_completer_id = {cfg_bus_number, cfg_device_number, cfg_function_number};

    IBUFDS_GTE2 i_pcie_refclk_ibuf (
        .O     (pcie_refclk),
        .ODIV2 (),
        .I     (pcie_clk_p),
        .CEB   (1'b0),
        .IB    (pcie_clk_n)
    );

    wire core_rst_n = pcie_perst_n;

    captainusb_pcie_7x i_captainusb_pcie_7x (
        .pci_exp_txp (pcie_tx_p),
        .pci_exp_txn (pcie_tx_n),
        .pci_exp_rxp (pcie_rx_p),
        .pci_exp_rxn (pcie_rx_n),

        .sys_clk     (pcie_refclk),
        .sys_rst_n   (core_rst_n),

        .s_axis_tx_tdata  (s_axis_tx_tdata),
        .s_axis_tx_tkeep  (s_axis_tx_tkeep),
        .s_axis_tx_tlast  (s_axis_tx_tlast),
        .s_axis_tx_tready (s_axis_tx_tready),
        .s_axis_tx_tuser  (s_axis_tx_tuser),
        .s_axis_tx_tvalid (s_axis_tx_tvalid),

        .m_axis_rx_tdata  (m_axis_rx_tdata),
        .m_axis_rx_tkeep  (m_axis_rx_tkeep),
        .m_axis_rx_tlast  (m_axis_rx_tlast),
        .m_axis_rx_tready (m_axis_rx_tready),
        .m_axis_rx_tuser  (m_axis_rx_tuser),
        .m_axis_rx_tvalid (m_axis_rx_tvalid),

        .cfg_mgmt_dwaddr        (10'h000),
        .cfg_mgmt_byte_en       (4'h0),
        .cfg_mgmt_do            (),
        .cfg_mgmt_rd_en         (1'b0),
        .cfg_mgmt_rd_wr_done    (),
        .cfg_mgmt_wr_readonly   (1'b0),
        .cfg_mgmt_wr_rw1c_as_rw (1'b0),
        .cfg_mgmt_di            (32'h00000000),
        .cfg_mgmt_wr_en         (1'b0),

        .cfg_interrupt_assert         (cfg_interrupt_assert),
        .cfg_interrupt                (cfg_interrupt),
        .cfg_interrupt_mmenable       (cfg_interrupt_mmenable),
        .cfg_interrupt_msienable      (cfg_interrupt_msienable),
        .cfg_interrupt_msixenable     (cfg_interrupt_msixenable),
        .cfg_interrupt_msixfm         (cfg_interrupt_msixfm),
        .cfg_pciecap_interrupt_msgnum (cfg_pciecap_interrupt_msgnum),
        .cfg_interrupt_rdy            (cfg_interrupt_rdy),
        .cfg_interrupt_do             (cfg_interrupt_do),
        .cfg_interrupt_stat           (cfg_interrupt_stat),
        .cfg_interrupt_di             (cfg_interrupt_di),

        .cfg_ds_bus_number       (cfg_bus_number),
        .cfg_ds_device_number    (cfg_device_number),
        .cfg_ds_function_number  (cfg_function_number),
        .cfg_dsn                 (64'h4355534200000001),
        .cfg_pm_force_state      (2'b00),
        .cfg_pm_force_state_en   (1'b0),
        .cfg_pm_halt_aspm_l0s    (1'b0),
        .cfg_pm_halt_aspm_l1     (1'b0),
        .cfg_pm_send_pme_to      (1'b0),
        .cfg_pm_wake             (1'b0),
        .rx_np_ok                (1'b1),
        .rx_np_req               (1'b1),
        .cfg_trn_pending         (1'b0),
        .cfg_turnoff_ok          (1'b1),
        .tx_cfg_gnt              (1'b1),
        .fc_cpld                 (),
        .fc_cplh                 (),
        .fc_npd                  (),
        .fc_nph                  (),
        .fc_pd                   (),
        .fc_ph                   (),
        .fc_sel                  (3'b000),

        .cfg_command       (),
        .cfg_bus_number    (cfg_bus_number),
        .cfg_device_number (cfg_device_number),
        .cfg_function_number (cfg_function_number),
        .cfg_root_control_pme_int_en (),
        .cfg_bridge_serr_en (),
        .cfg_dcommand (),
        .cfg_dcommand2 (),
        .cfg_dstatus (),
        .cfg_lcommand (),
        .cfg_lstatus (),
        .cfg_pcie_link_state (),
        .cfg_pmcsr_pme_en (),
        .cfg_pmcsr_pme_status (),
        .cfg_pmcsr_powerstate (),
        .cfg_received_func_lvl_rst (),
        .cfg_status (),
        .cfg_to_turnoff (),
        .tx_buf_av (),
        .tx_cfg_req (),
        .tx_err_drop (),
        .cfg_vc_tcvc_map (),
        .cfg_aer_rooterr_corr_err_received (),
        .cfg_aer_rooterr_corr_err_reporting_en (),
        .cfg_aer_rooterr_fatal_err_received (),
        .cfg_aer_rooterr_fatal_err_reporting_en (),
        .cfg_aer_rooterr_non_fatal_err_received (),
        .cfg_aer_rooterr_non_fatal_err_reporting_en (),
        .cfg_root_control_syserr_corr_err_en (),
        .cfg_root_control_syserr_fatal_err_en (),
        .cfg_root_control_syserr_non_fatal_err_en (),
        .cfg_slot_control_electromech_il_ctl_pulse (),
        .cfg_msg_received (),
        .cfg_msg_data (),
        .cfg_msg_received_err_cor (),
        .cfg_msg_received_err_non_fatal (),
        .cfg_msg_received_err_fatal (),
        .cfg_msg_received_pm_as_nak (),
        .cfg_msg_received_pm_pme (),
        .cfg_msg_received_pme_to_ack (),
        .cfg_msg_received_assert_int_a (),
        .cfg_msg_received_assert_int_b (),
        .cfg_msg_received_assert_int_c (),
        .cfg_msg_received_assert_int_d (),
        .cfg_msg_received_deassert_int_a (),
        .cfg_msg_received_deassert_int_b (),
        .cfg_msg_received_deassert_int_c (),
        .cfg_msg_received_deassert_int_d (),
        .cfg_msg_received_setslotpowerlimit (),

        .cfg_err_ecrc                  (1'b0),
        .cfg_err_ur                    (1'b0),
        .cfg_err_cpl_timeout           (1'b0),
        .cfg_err_cpl_unexpect          (1'b0),
        .cfg_err_cpl_abort             (1'b0),
        .cfg_err_posted                (1'b0),
        .cfg_err_cor                   (1'b0),
        .cfg_err_atomic_egress_blocked (1'b0),
        .cfg_err_internal_cor          (1'b0),
        .cfg_err_malformed             (1'b0),
        .cfg_err_mc_blocked            (1'b0),
        .cfg_err_poisoned              (1'b0),
        .cfg_err_norecovery            (1'b0),
        .cfg_err_tlp_cpl_header        (48'h000000000000),
        .cfg_err_cpl_rdy               (),
        .cfg_err_locked                (1'b0),
        .cfg_err_acs                   (1'b0),
        .cfg_err_internal_uncor        (1'b0),
        .cfg_err_aer_headerlog         (128'h00000000000000000000000000000000),
        .cfg_aer_interrupt_msgnum      (5'h00),
        .cfg_err_aer_headerlog_set     (),
        .cfg_aer_ecrc_check_en         (),
        .cfg_aer_ecrc_gen_en           (),

        .pl_initial_link_width (),
        .pl_phy_lnk_up (),
        .pl_lane_reversal_mode (),
        .pl_link_gen2_cap (),
        .pl_link_partner_gen2_supported (),
        .pl_link_upcfg_cap (),
        .pl_sel_lnk_rate (),
        .pl_sel_lnk_width (),
        .pl_ltssm_state (),
        .pl_rx_pm_state (),
        .pl_tx_pm_state (),
        .pl_directed_change_done (),
        .pl_received_hot_rst (),
        .pl_directed_link_auton (1'b0),
        .pl_directed_link_change (2'b00),
        .pl_directed_link_speed (1'b0),
        .pl_directed_link_width (2'b00),
        .pl_upstream_prefer_deemph (1'b1),
        .pl_transmit_hot_rst (1'b0),
        .pl_downstream_deemph_source (1'b0),

        .pcie_drp_clk  (clk_sys),
        .pcie_drp_en   (1'b0),
        .pcie_drp_we   (1'b0),
        .pcie_drp_addr (9'h000),
        .pcie_drp_di   (16'h0000),
        .pcie_drp_rdy  (),
        .pcie_drp_do   (),

        .user_clk_out   (pcie_user_clk),
        .user_reset_out (pcie_user_reset),
        .user_lnk_up    (pcie_link_up),
        .user_app_rdy   (user_app_rdy)
    );

    wire unused_core_reset = rst;
    wire unused_user_app_rdy = user_app_rdy;
endmodule
